### ISSUE TITLE
如果我不希望包内的route生效, 怎么做?

### ISSUE THREAD

**Issue by RJustice** [ForoneTech/ForoneAdministrator#1]
除了注释掉 foroneserviceprovider 内的route注册之外, 还有其他方法吗?
因为其中有一处就是adminsController的处理, 使用的验证都是验证admins表重复, 但是使用auth来说是使用的users表, 因为我前后台都有登陆.  本来想要区分使用admins 和 users表, 但是需要更改的好多. 不适合以后更新.

> _<

感谢

**Comment by mani95lisa** [comment]
有点没看明白呢，不希望包内route生效的话，可以试试用命令行把route缓存起来，目前是没有缓存的时候才加载的模块里的路由。

```
if (!$this->app->routesAreCached()) {
            require __DIR__ . '/../routes.php';
        }
```

如果只是因为表的问题的话，可以修改下后台管理系统的`auth.php`配置里的`modal`，默认是`App\User`，你可以改成别的，就会默认校验别的表了。

如果是因为前端和后台管理系统都在同一个系统里，需要区分User和Admin的登录的话，可以试试[multiauth](https://github.com/ollieread/multiauth/tree/laravel5)，不过现在我们没有加入这个部分呢，一般来说后台管理系统和前端的系统都是分离的。

有问题再沟通~

**Comment by mani95lisa** [comment]
@RJustice 加入了新的forone配置属性，可以直接禁用所有自带的routes

**Comment by RJustice** [comment]
赞的, 感谢. 已更新.

**Comment by mani95lisa** [comment]
@RJustice 现在先是放到了dev-master里，回头再加点功能再打个标签。还加了管理员表的配置和AuthController的配置，有问题再随时沟通~

**Comment by mani95lisa** [comment]
@RJustice 加多了一个forone:copy的命令，可以把routes和相关的Controllers都copy到项目里，然后就可以全部自定义了
