### ISSUE TITLE
安装时报错 zizaco/entrust

### ISSUE THREAD

**Issue by cssailing** [ForoneTech/ForoneAdministrator#13]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for forone/administrator ~1.1.1 -> satisfiable by forone/administrator[1.1.1].
    - forone/administrator 1.1.1 requires zizaco/entrust dev-laravel-5@dev -> no matching package found.

Potential causes:
- A typo in the package name
- The package is not available in a stable-enough version according to your minimum-stability setting
  see https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion for more details.

Read https://getcomposer.org/doc/articles/troubleshooting.md for further common problems.

**Comment by mani95lisa** [comment]
@cssailing composer里加下 "minimum-stability": "dev" ，entrust之前没正式版本

**Comment by cssailing** [comment]
这个插件已经有正式版本了
"zizaco/entrust": "dev-laravel-5"
是不是可以更新一下

**Comment by cssailing** [comment]
已经看到更新了。
谢谢
