### ISSUE TITLE
下拉列表怎么用blade中的foreach呢

### ISSUE THREAD

**Issue by maxiaoxiong** [ForoneTech/ForoneAdministrator#15]
`{!! Form::form_select('type_id', '标的类型', [
@foreach($results as $result)
    ['label'=>'名称', 'value'=>''],
@endforeach
],0.5,false) !!}`
这个代码会报错，不知道怎么处理

**Comment by mani95lisa** [comment]
就直接把那个数组作为参数传进去就行了，数组嵌套到模板里就行了，{!!里不能用blade语法的

**Comment by maxiaoxiong** [comment]
@mani95lisa 谢谢，解决了，之前对与laravel的eloquent不很了解．
