### ISSUE TITLE
Fatal error: Class 'Route' not found

### ISSUE THREAD

**Issue by Barbery** [ForoneTech/ForoneAdministrator#16]
安装完，且按照说明配置了config/app.php的providers和aliases，运行php artisan vendor:publish报错如下：
  [Symfony\Component\Debug\Exception\FatalThrowableError]
  Fatal error: Class 'Route' not found

**Comment by hhxiaohei** [comment]
@Barbery 
请问您是哪个版本的Laravel?
不同的版本具体的修改方法也不太一样,可以切换分支查看使用说明
5.1版本的修改这些
`'providers' => [
    Forone\Providers\ForoneServiceProvider::class
]
'aliases' => [
    'Form'      => Illuminate\Html\FormFacade::class,
    'Html'      => Illuminate\Html\HtmlFacade::class,
    'Entrust'   => Zizaco\Entrust\EntrustFacade::class
]`
5.2的则是修改
`'providers' => [
    Collective\Html\HtmlServiceProvider::class,
    Forone\Providers\ForoneServiceProvider::class,
]
'aliases' => [
    'Form' => Collective\Html\FormFacade::class,
    'Html' => Collective\Html\HtmlFacade::class,
    'Entrust'   => Zizaco\Entrust\EntrustFacade::class,
]`
你可以再试试看

**Comment by Barbery** [comment]
这个issue好久了，已弃坑。。。
