### ISSUE TITLE
发现按钮点击修改字段值的小问题

### ISSUE THREAD

**Issue by alex-linxs** [ForoneTech/ForoneAdministrator#18]
第三项的“点击按钮后需要修改某个字段为某个值”,点击更改后报错，并没有更新该值，主要是formButton（）函数uri没有写对，把 if (!array_key_exists('uri', $config)) {
                // // $config['uri'] = 'update';
                // //修改为
                $config['uri']=$config['id'];
            }，就可以修改字段值了

**Comment by mani95lisa** [comment]
uri就是在外面写死的，这是没有的情况下默认访问update
