### ISSUE TITLE
创建管理员时提示没有数据库

### ISSUE THREAD

**Issue by yanqing6628780** [ForoneTech/ForoneAdministrator#2]
**SQLSTATE[42S02]: Base table or view not found: 1146 Table 'homestead.admins' doesn't exist (SQL: select count(*) as aggregate from `admins` where `email` = user@admin.com)**

在`database\migrations`文件夹下也没看到有admin数据库创建文件。

**Comment by mani95lisa** [comment]
有运行 `php artisan vendor:publish` 吗

**Comment by yanqing6628780** [comment]
有运行啊。其他几个表的数据添加是正常的。
而且，我看过数据库，就是没有admin的表。
![qq 20150828153240](https://cloud.githubusercontent.com/assets/8479740/9543275/4af87f90-4daa-11e5-81ea-443f73b25a0b.png)

**Comment by RJustice** [comment]
这个错误是在 forone\administrator\src\Forone\Requests\CreateAdminRequest.php  这个文件中, 使用了验证admins表的unique. 

UpdateAdminRequest.php 中也有验证admins表的unique;

**Comment by RJustice** [comment]
updateAdminRequest里面没... 弄错了...

**Comment by mani95lisa** [comment]
@RJustice 验证为unique跟数据库表不存在没关系呢，有运行 `php artisan forone:init`吗

**Comment by RJustice** [comment]
CreateAdminRequest 
public function rules()
    {
        return [
            'name' => 'required|max:20',
            'email' => 'required|email|unique:admins',
            'password' => 'required|max:20',
        ];
    }

代码里面有验证 admins表, 

init中没有创建admins表哦... 我估计问题就是这个. ^_^. 他没有创建admins表, 然后还需要配置里面配置一下  config/forone.php , 使用table为admins.

**Comment by mani95lisa** [comment]
@RJustice 哦哦，明白了，之前升级的时候出的bug，稍后我们改下，多谢啦~
