### ISSUE TITLE
安装失败

### ISSUE THREAD

**Issue by meitesi** [ForoneTech/ForoneAdministrator#29]
./composer.json has been updated
Loading composer repositories with package information

Installation failed, reverting ./composer.json to its original content.

  [Composer\Downloader\TransportException]
  Your configuration does not allow connections to http://git.nxdai.com/mani/ForoneAdmin
  istrator.git. See https://getcomposer.org/doc/06-config.md#secure-http for details.

require [--dev] [--prefer-source] [--prefer-dist] [--no-plugins] [--no-progress] [--no-upda
te] [--update-no-dev] [--update-with-dependencies] [--ignore-platform-reqs] [--sort-package
s] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--] [<packages>]...

D:\phpStudy\WWW\blog>composer require forone/administrator:5.1.x
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package forone/administrator 5.1.x is satisfiable by forone/administrat
or[5.1.x-dev] but those are rejected by your minimum-stability.
  Problem 2
    - The requested package minimum-stability could not be found in any version, there may
be a typo in the package name.

Potential causes:
- A typo in the package name
- The package is not available in a stable-enough version according to your minimum-stabil
  ity setting
  see https://getcomposer.org/doc/04-schema.md#minimum-stability for more details.

Read https://getcomposer.org/doc/articles/troubleshooting.md for further common problems.

Installation failed, reverting ./composer.json to its original content.

**Comment by mani95lisa** [comment]
是国内的源没有更新，刚更新，也可以直接用github的源进行安装
