### ISSUE TITLE
创建管理员的BUG

### ISSUE THREAD

**Issue by lllliuliu** [ForoneTech/ForoneAdministrator#3]
创建管理员的时候会报错，因为使用了
 $registrar->create($request->only(['name', 'password', 'email']));
默认为admins表，需要修改逻辑为users表

**Comment by mani95lisa** [comment]
@lllliuliu 多谢，我们修改下，把它改成配置

**Comment by zxwzyt** [comment]
@lllliuliu 是下的最新版的吗？默认的表格就是users呀?

**Comment by lllliuliu** [comment]
composer显示：
 "name": "forone/administrator", 
 "version": "1.0.1",  
 ....
"time": "2015-08-23 14:27:57"

**Comment by zxwzyt** [comment]
@lllliuliu 这不是最新版本的，更新到最新版本就好了

**Comment by lllliuliu** [comment]
=。=！！！
原来如此

**Comment by lllliuliu** [comment]
感谢

**Comment by zxwzyt** [comment]
@lllliuliu 客气了，不用谢

**Comment by mani95lisa** [comment]
@lllliuliu 你用 ~1.0.0 这个版本号就会自动匹配最新的1.0系列版本了
