### ISSUE TITLE
HtmlServiceProvider内的一个小bug?

### ISSUE THREAD

**Issue by RJustice** [ForoneTech/ForoneAdministrator#5]
<script src="https://gist.github.com/RJustice/5b8afc535e10d4fdec0a.js"></script>

这个panel_start 和 panel_end 不配套, 
panel_end没有闭合panel_start开启的标签

**Comment by zxwzyt** [comment]
我这边测试是配套的呀，再试一下呢？或者能把页面截个图吗？
