### ISSUE TITLE
依靠配置文件？

### ISSUE THREAD

**Issue by dryyun** [ForoneTech/ForoneAdministrator#7]
您做的管理系统我用了一下，据我说看到的，您的很多设置，包括权限设置，url设置等都是跟配置文件有关的，这样做是不是不太灵活？如果作为使用人员就不能任意的修改。

**Comment by mani95lisa** [comment]
是这样的，后台管理系统的菜单增加取消其实都会涉及到相应的功能页面研发，不是简单的使用人员配置就可以增加或删除的。

另外，使用人员可以通过权限控制来调整显示的菜单等，一般也不存在说非得要随时改下菜单名称或icon之类的需求，如果有这样需要的话，就需要单独做一个表或者读写文件来存储了。

**Comment by dryyun** [comment]
了解了
