### ISSUE TITLE
操作几次后总是会被重定向到登陆界面

### ISSUE THREAD

**Issue by xboy2006** [ForoneTech/ForoneAdministrator#86]
正常登陆后， 做几次操作后，会被重定向到登陆界面。 暂时没有发现什么规律。请问应该如何排查这个问题呢

**Comment by hhxiaohei** [comment]
@xboy2006 感谢反馈,频率一般是多久?将您.env 中的CACHE_DRIVER改为 redis 试试

**Comment by rossli** [comment]
@xboy2006  如果你禁用了自带 routes, 那么 修改 此组件的routes 首页跳转,如图,如果用自带routes,检查一下 routes这种写法, 修改之前的写法是错误的
[![](http://o9zn2jdiq.bkt.clouddn.com/ForoneAdministrator_routes_php_at_master_%C2%B7_ForoneTech_ForoneAdministrator.png)](www.romanysoft.com)

**Comment by rossli** [comment]
已修复
 https://github.com/ForoneTech/ForoneAdministrator/pull/94
