### ISSUE TITLE
手机UC浏览器登入后，菜单栏无法调出

### ISSUE THREAD

**Issue by guiduan** [ForoneTech/ForoneAdministrator#87]
手机UC浏览器登入后，菜单栏无法调出。

**Comment by rossli** [comment]
@guiduan  感谢反馈 , 刚测试了  iphone 6s, 最新版 UC 是可以的啊,你是 安卓?

**Comment by guiduan** [comment]
@rossli 是的，我是安卓，安卓自带的浏览器都正常，唯独UC不正常。

**Comment by guiduan** [comment]
@rossli 刚刚我又测试了一下，把原先的uc（11.1.15.871）升级到（11.5.2.942）之后，能正常显示了。
