### ISSUE TITLE
git clone composer install 然后 require报错 

### ISSUE THREAD

**Issue by dynamohuang** [ForoneTech/ForoneAdministrator#88]
求一个可用的安装方法

1，git clone
2，composer install
3，按照read me 添加
"repositories": [
  {"type": "git", "url": "http://git.nxdai.com/mani/ForoneAdministrator.git"},
  {"type": "composer", "url": "http://packagist.phpcomposer.com"},
  {"packagist": false}
],
"minimum-stability" : "dev"
由于启用了 "minimum-stability" : "dev"，Laravel的dev版本会导致paginate出错，请在composer.json里将laravel版本设置为确定的版本号，例如5.1.4  这里也改为指定的5.2.1了

报错信息 
Problem 1
    - Can only install one of: zizaco/entrust[5.2.x-dev, dev-laravel-5].
    - Can only install one of: zizaco/entrust[dev-laravel-5, 5.2.x-dev].
    - Can only install one of: zizaco/entrust[5.2.x-dev, dev-laravel-5].
    - Installation request for zizaco/entrust 5.2.x-dev -> satisfiable by zizaco/entrust[5.2.x-dev].
    - Installation request for zizaco/entrust (locked at dev-laravel-5, required as 5.2.x-dev) -> satisfiable by zizaco/entrust[dev-laravel-5].

**Comment by hhxiaohei** [comment]
@dynamohuang 感谢反馈,请尝试以下方案,我这边测试成功

- 1.`composer create-project laravel/laravel:5.2.31 foronedemo`
- 2.编辑 `composer.json`文件
- 2.1.修改 `"laravel/framework":"5.2.45"`
- 2.2. 添加`"minimum-stability" : "dev"`
- 3.`composer require forone/administrator:5.2.x-dev`
- 4.按照文档执行后续操作

**Comment by dynamohuang** [comment]
@hhxiaohei 感谢你的解答，按照你的解答能够顺利安装了。
是我之前没理解对，原来这个项目是个composer组件，得先新建laravel项目，再composer安装。
不错的项目，努力学习ing，希望以后有机会也能参与进来，提出有价值的pull request

**Comment by mani95lisa** [comment]
@dynamohuang 如果没有别的问题就把问题关掉啦。
